# Generated by Django 5.0.6 on 2024-05-23 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('time_to_cook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('recipe', models.TextField()),
                ('price', models.CharField(max_length=200)),
                ('cooking_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cateogory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('time_to_cook_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='time_to_cook.timetocook')),
            ],
            options={
                'db_table': 'dish',
            },
        ),
    ]
