# Generated by Django 5.0.4 on 2024-05-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cooking_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
